### PR TITLE
v3.1.0 (Mirroring Improvements & Auto Replication)

### LINKED ISSUE #246: Features for Mirroring and Downloading
### Package Versions

Replace the values below using the output from `npm list storj`. Use `npm list -g storj` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```
### Expected Behavior
- Allow mirroring of all files inside a buckets at once.
- Allow the user to check how many mirrors have been created for a specific file.
- Inform the user at mirroring how many mirrors have already been created and how many can still be created
- If no more mirrors can be created for a file the user is informed on this matter.
 - Allow a user to download all the files inside a bucket at once.
### Actual Behavior
- We can only mirror one file at a time.
- A user does not know if the file is already mirrored or not, and how many mirrors are currently in circulation for that specific file.
- Currently a user wanting to download all the files inside a specific bucket has to download all files one-by-one. This can be achieved by for example: `storj upload-file <Bucket ID> /*`   , `/*` meaning all files. The same would apply to mirroring all files inside of a bucket.

### LINKED ISSUE #276: Automatic replication when failed download reported
* Replicate to 1 node when a download fails
* Replicate to N nodes when an upload succeeds

### PR DESCRIPTION
**Pull request by bookchin**
* Closes #246 
* Closes #276

---

Related to https://github.com/Storj/core-cli/pull/73, https://github.com/Storj/complex/pull/32, and https://github.com/Storj/core/pull/574

### CODE REVIEW

**Comment by braydonf** [comment]
Tested with https://github.com/braydonf/storj-integration/tree/mirror with a ~300MB file and replication was automatically established after uploading. There were 2 shards out of 23 that had 2 mirrors instead of 3 (the max being 3 since there are only 4 farmers).

File: lib/server/routes/reports.js [hunk 1]
```diff
@@ -49,6 +52,8 @@ ReportsRouter.prototype.createExchangeReport = function(req, res, next) {
 
     // TODO: Add signature/identity verification
 
+    // NB: Kick off mirroring if needed
+    self._handleExchangeReport(exchangeReport, () => null);
```
Comment (braydonf) [inline lib/server/routes/reports.js]: Should we add log message if error here?

**Comment by braydonf** [comment]
Code review looks good, database calls should have indexes to avoid any performance issues.
